export const INIT_VIEW = 'INIT_VIEW';

export const EPIC_ACTION_START_DRAW = 'EPIC_ACTION_START_DRAW';
export const EPIC_ACTION_CANCEL_DRAW = 'EPIC_ACTION_CANCEL_DRAW';
export const EPIC_ACTION_END_DRAW = 'EPIC_ACTION_END_DRAW';
export const EPIC_ACTION_SYMBOL = 'EPIC_ACTION_SYMBOL';
